### ISSUE TITLE
Adapt/retire SquareLine-based example

### ISSUE THREAD

**Issue by aliphys** [arduino-libraries/Arduino_GigaDisplay#27]
As highlighted by @leonardocavagnis in https://github.com/arduino-libraries/Arduino_GigaDisplay/pull/22:
> Cannot port squarelinestudio_lvgl to v9 because [SquareLine Studio is no longer compatible with LVGL](https://blog.lvgl.io/2024-02-12/sls-break-up). It works only with v8 and earlier.

The [squarelinestudio_lvgl_v8.ino](https://github.com/arduino-libraries/Arduino_GigaDisplay/blob/de47486471e46d0c6f9d0e5fc3395407910ad44e/examples/lvgl/squarelinestudio_lvgl_v8/squarelinestudio_lvgl_v8.ino) is not longer relevant and should be adapted/deleted since:
- It is not part of the examples we want our Users to interact with
- The code is not expected to compile (and is not included as part of the `compile-example.yml` workflow) https://github.com/arduino-libraries/Arduino_GigaDisplay/blob/de47486471e46d0c6f9d0e5fc3395407910ad44e/.github/workflows/compile-examples.yml#L30-L50

## Possible solutions

|Option|Positive|Negative|
|-|-|-|
|Remove|Quick and easy fix, reduced future maintenance. No Zendesk tickets mentioning this _specific_ example, so should have minimal affect on Users|Library functionality scope reduced|
|Adapt|Retain compatibility with SquareLine Studio|Additional effort for a [discontinued feature](https://forum.lvgl.io/t/lvgl-ends-its-collaboration-with-squareline-studio/14638/19)|

**Comment by per1234** [comment]
I don't have any opinion regarding whether or not the example should be removed. However, it should be noted that SquareLine Studio have stated they do plan to provide LVGL 9.x support:

https://forum.squareline.io/t/q-plans-timeline-for-lvgl-9-observer-support/2782/2

> LVGL9 support is planned for the upcoming April release. (And we’d like to support observers in the future.)

The library/core have backwards compatibility with LVGL 8.x, so it is still possible for users to use this example by simply installing version 8.4.0 of the "**lvgl**" library.

**Comment by leonardocavagnis** [comment]
I'm agree with @per1234.
Do not retire [squarelinestudio_lvgl_v8.ino](https://github.com/arduino-libraries/Arduino_GigaDisplay/blob/de47486471e46d0c6f9d0e5fc3395407910ad44e/examples/lvgl/squarelinestudio_lvgl_v8/squarelinestudio_lvgl_v8.ino), we'll do the porting to LVGLv9 when the new SquareLine studio will be release.

**Comment by aliphys** [comment]
Thanks for the insight @per1234 and @leonardocavagnis . Closing this issue, and created issue https://github.com/arduino-libraries/Arduino_GigaDisplay/issues/29 regarding the porting task @leonardocavagnis mentioned.
