### ISSUE TITLE
RGB.on Green & Blue Values possibly switched?

### ISSUE THREAD

**Issue by LminusSucksAtCoding** [arduino-libraries/Arduino_GigaDisplay#9]
Hi, We have recently gotten a Gigadisplay board and were toying with the example code for the RGB LED.
Running:
`rgb.on(0, 0, 255) // Turn on Blue Pixel`
unexpectedly turned on our green LED, similarly running:
`rgb.on(0, 255, 0)`
turned on our blue led

Looking at the [source code]( https://github.com/arduino-libraries/Arduino_GigaDisplay/blob/de25be33e46dff122ee2f3e2d58261f288aaf890/src/GigaDisplayRGB.cpp#L15C1-L18C27), I noticed
> void GigaDisplayRGB::on(uint8_t r, uint8_t g, uint8_t b)
> {
>     writeByte(0x10, r);
>     writeByte(0x12, g);
>     writeByte(0x11, b);
>     writeByte(0x2b, 0xc5);
> }

Could it be that the writeByte for G:0x12 and B:0x11 be swapped?
> void GigaDisplayRGB::on(uint8_t r, uint8_t g, uint8_t b)
> {
>     writeByte(0x10, r);
>     writeByte(0x11, g);
>     writeByte(0x12, b);
>     writeByte(0x2b, 0xc5);
> }

**Comment by karlsoderby** [comment]
Hi there @LminusSucksAtCoding , you are correct. Fixed in #12 , thanks for reporting it!
